### PR TITLE
Add the Box Least Squares (BLS) & Lightkurve tutorials

### PR DESCRIPTION
**Pull request by barentsen**
This PR adds a tutorial on the use of the Box Least Squares (BLS) algorithm.

### CODE REVIEW

**Comment by ceb8** [comment]
Thanks @barentsen. Can you also add links to this tutorial (and the lightkurve one) to the main README?

**Comment by barentsen** [comment]
@ceb8 Sure thing!  I pushed an extra commit to update the main README just now!

**Comment by barentsen** [comment]
Oops ... I forgot to add a section to the README for lightkurve.  One moment!

**Comment by barentsen** [comment]
@ceb8 I finished adding a section for Lightkurve to the main README, and updated its materials while at it.  Feel free to merge!

**Comment by ceb8** [comment]
Thanks @barentsen!

**Pull request merged**
