### PR TITLE
Starspot mapping tutorial

### PR DESCRIPTION
**Pull request by rodluger**
One of two `starry` tutorials. I'm still working on a more basic introductory tutorial, will add commits to this PR in the next day or so.

### CODE REVIEW

**Comment by ceb8** [comment]
@rodluger Thanks for this! If you could ping me when you take this out of WIP status that would be helpful.

Also, could you add an entry to the README pointing to your tutorials when you are done?

**Comment by rodluger** [comment]
Will do, thanks!

**Comment by rodluger** [comment]
@ceb8 I updated the PR with the other tutorial, and it's ready for merging. Thanks!

**Comment by ceb8** [comment]
Merged! Thanks @rodluger!

**Pull request merged**
